# bump-version.ps1 — Auto-increments versionCode and versionName in build.gradle
# and writes public/js/version.js for in-app version display.
# Called automatically by build-release.bat before every build.

$gradlePath    = "$PSScriptRoot\app\build.gradle"
$versionJsPath = "$PSScriptRoot\..\public\js\version.js"

$content = [System.IO.File]::ReadAllText($gradlePath, [System.Text.Encoding]::UTF8)

# ── Read current versionCode ───────────────────────────────────────────────
$codeMatch = [regex]::Match($content, 'versionCode\s+(\d+)')
if (-not $codeMatch.Success) { Write-Error "versionCode not found in build.gradle"; exit 1 }
$currentCode = [int]$codeMatch.Groups[1].Value
$newCode     = $currentCode + 1

# ── Read current versionName and increment minor (e.g. "1.3" -> "1.4") ───
$nameMatch = [regex]::Match($content, 'versionName\s+"([^"]+)"')
if (-not $nameMatch.Success) { Write-Error "versionName not found in build.gradle"; exit 1 }
$currentName = $nameMatch.Groups[1].Value
$parts       = $currentName.Split('.')
$parts[$parts.Length - 1] = [string]([int]$parts[$parts.Length - 1] + 1)
$newName     = $parts -join '.'

# ── Write back to build.gradle ─────────────────────────────────────────────
$content = $content -replace 'versionCode\s+\d+',       "versionCode $newCode"
$content = $content -replace 'versionName\s+"[^"]+"',   "versionName `"$newName`""
[System.IO.File]::WriteAllText($gradlePath, $content, [System.Text.Encoding]::UTF8)

# ── Write public/js/version.js ─────────────────────────────────────────────
$today     = Get-Date -Format 'yyyyMMdd'
$verJs     = "// Auto-generated by build-release.bat — do not edit manually`n"
$verJs    += "const APP_VERSION = { code: $newCode, name: '$newName', build: '$today' };`n"
[System.IO.File]::WriteAllText($versionJsPath, $verJs, [System.Text.Encoding]::UTF8)

Write-Host "  versionCode : $currentCode -> $newCode"
Write-Host "  versionName : $currentName -> $newName"
Write-Host "  version.js  : updated (build $today)"
