# bump-version.ps1 — Auto-increments versionCode and versionName in build.gradle
# and writes public/js/version.js for in-app version display.
# Called automatically by build-release.bat before every build.

$gradlePath    = "$PSScriptRoot\app\build.gradle"
$versionJsPath = "$PSScriptRoot\..\public\js\version.js"

# Always write without BOM — Gradle requires plain UTF-8, no BOM
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

# Read with Get-Content -Raw (PowerShell handles BOM detection safely)
$content = Get-Content $gradlePath -Raw -Encoding UTF8

# ── Read current versionCode ───────────────────────────────────────────────
$codeMatch = [regex]::Match($content, 'versionCode\s+(\d+)')
if (-not $codeMatch.Success) { Write-Error "versionCode not found in build.gradle"; exit 1 }
$currentCode = [int]$codeMatch.Groups[1].Value
$newCode     = $currentCode + 1

# ── Read current versionName and increment minor (e.g. "1.4" -> "1.5") ───
$nameMatch = [regex]::Match($content, 'versionName\s+"([^"]+)"')
if (-not $nameMatch.Success) { Write-Error "versionName not found in build.gradle"; exit 1 }
$currentName = $nameMatch.Groups[1].Value
$parts       = $currentName.Split('.')
$parts[$parts.Length - 1] = [string]([int]$parts[$parts.Length - 1] + 1)
$newName     = $parts -join '.'

# ── Write back to build.gradle (no BOM) ───────────────────────────────────
$content = $content -replace 'versionCode\s+\d+',     "versionCode $newCode"
$content = $content -replace 'versionName\s+"[^"]+"', "versionName `"$newName`""
[System.IO.File]::WriteAllText($gradlePath, $content, $utf8NoBom)

# ── Write public/js/version.js (no BOM) ───────────────────────────────────
$today  = Get-Date -Format 'yyyyMMdd'
$verJs  = "// Auto-generated by build-release.bat -- do not edit manually`n"
$verJs += "const APP_VERSION = { code: $newCode, name: '$newName', build: '$today' };`n"
[System.IO.File]::WriteAllText($versionJsPath, $verJs, $utf8NoBom)

Write-Host "  versionCode : $currentCode -> $newCode"
Write-Host "  versionName : $currentName -> $newName"
Write-Host "  version.js  : updated (build $today)"
